### PR TITLE
PLANNER-617: Workbench: Construction Heuristics - Add support for EntitySorterManner

### PR DESCRIPTION
**Pull request by mcimbora**
Depends on https://github.com/droolsjbpm/optaplanner-wb/pull/115

### CODE REVIEW

**Comment by mcimbora** [comment]
Jenkins retest this

**Comment by mcimbora** [comment]
Pushed updated version.

**Comment by mcimbora** [comment]
Jenkins retest this.

**Comment by csadilek** [comment]
+1

**Pull request merged**
