### PR TITLE
PLANNER-709: Workbench: Data object and fields can not be accessed from guided rule

### PR DESCRIPTION
**Pull request by mcimbora**
Fire ApplicationStarted event (https://github.com/kiegroup/optaplanner-wb/pull/178/files#diff-feba0cbb3f97e7c625b0e9d445c49d13R78) to keep track of path updates.

@ederign Could you please review the PR? Thanks in advance.

### CODE REVIEW

**Comment by mcimbora** [comment]
Jenkins retest this.

**Comment by ge0ffrey** [comment]
@mcimbora would you mind resolving the conflicts?

**Comment by mcimbora** [comment]
@ge0ffrey Done.

**Comment by mcimbora** [comment]
Jenkins retest this.

**Comment by ge0ffrey** [comment]
jenkins retest this

**Pull request merged**
