### PR TITLE
PLANNER-574: Workbench: Include client classes from drools-wb, guvnor, kie-wb-common projects in exclusion list of optaplanner-wb-webapp.beans.xml

### PR DESCRIPTION
**Pull request by mcimbora**

### CODE REVIEW

**Comment by csadilek** [comment]
Just a clarification here regarding the comment in the beans.xml file and to make sure we're on the same page. These exclusion are _not_ needed for Errai but for Weld (server-side CDI) which will find and try to load these classes otherwise. This is also only relevant in SuperDevMode where all this classes are on the classpath (we're using an embedded WF so we only need to run one JVM). In production, because we've set all these dependencies to provided, these types (and jars) won't be present and don't need to be excluded from the scan (of course, you can still use the same beans.xml).

**Comment by mcimbora** [comment]
@csadilek Thanks for the detailed explanation. I'll keep the file aligned to https://github.com/droolsjbpm/drools-wb/blob/master/drools-wb-webapp/src/main/webapp/WEB-INF/beans.xml#L4 (as the lines are auto appended there anyway) if that makes sense to you.

**Comment by csadilek** [comment]
@mcimbora ok, I guess, I would just remove/update the comment in beans.xml so it doesn't cause confusion for others.

+1, in any case.

**Comment by ge0ffrey** [comment]
@mcimbora Would you mind adjusting the comment above those excludes to match @csadilek explanation that it's for weld (not for errai as it currently states). The sole purpose is of the comment is to make it clear to understand when this workaround is obsolete and we can delete that verbosity.

**Pull request merged**
