### PR TITLE
JBPM-4937: Data Modeler loading time very long and increasing with more 'instances'

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
@manstis Hello Mike, would you mind review this PR?
Thanks.

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Depends on: https://github.com/droolsjbpm/kie-wb-common/pull/319/

**Comment by csadilek** [comment]
6.4.x: f5f94e9bc29685c55c7e7d47efeeba8474466f04

**Pull request closed without merging**
