### PR TITLE
added dir /org.optaplanner to gitignore

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by ge0ffrey** [comment]
Can't we get the maven-zanata-plugin to generate this either:
- under the `target/zanata` directory, if it's desirable to be removed during `mvn clean`
- under the `local/zanata` directory, if it's not desirable to be removed during `mvn clean`

**Comment by ge0ffrey** [comment]
the maven help plugin is your friend. Bookmark the first line of the code snippet below :)

```
$ mvn help:describe -Dcmd=zanata:pull -Ddetail
...
[INFO] --- maven-help-plugin:2.2:describe (default-cli) @ optaplanner-wb ---
[INFO] 'zanata:pull' is a plugin goal (aka mojo).
Mojo: 'zanata:pull'
zanata:pull
  Description: Pulls translated text from Zanata.
  Implementation: org.zanata.maven.PullSimpleMojo
  Language: java

  Available parameters:

    createSkeletons
      User property: zanata.createSkeletons
      Whether to create skeleton entries for strings/files which have not been
      translated yet

    dryRun
      User property: dryRun
      Dry run: don't change any data, on the server or on the filesystem.

    enableModules
      User property: zanata.enableModules
      Whether module processing should be enabled. This option is obsolete.
      Please use pull-module instead.

    encodeTabs (Default: true)
      User property: zanata.encodeTabs
      Whether tabs should be encoded as \t (true) or left as tabs (false).

    fromDoc
      User property: zanata.fromDoc
      Specifies a document from which to begin the push operation. Documents
      before this document (sorted alphabetically) will not be pushed. For
      multi-module projects, the full document path including module id is
      required. Use this option to resume a failed push operation.

    includeFuzzy (Default: false)
      User property: zanata.includeFuzzy
      Whether to include fuzzy translations in translation files when using
      project type 'file'. If this option is false, source text will be used
      for any string that does not have an approved translation.

    interactiveMode (Default: ${settings.interactiveMode})
      Interactive mode is enabled by default, but can be disabled using Maven's
      -B/--batch-mode option.

    key
      User property: zanata.key
      API key for accessing the REST API. Defaults to the value in zanata.ini.

    locales
      User property: zanata.locales
      Locales to push to/pull from the server. By default all locales in
      zanata.xml will be pushed/pulled. Usage:
      -Dzanata.locales=locale1,locale2,locale3

    logHttp (Default: false)
      User property: zanata.logHttp
      Enable HTTP message logging.

    projectConfig (Default: ${basedir}/zanata.xml)
      User property: zanata.projectConfig
      Zanata project configuration file.

    projectType
      User property: zanata.projectType
      Type of project ( 'properties' = Java .properties, 'podir' =
      publican-style gettext directories, 'utf8properties' = UTF-8 .properties
      files, 'gettext' = gettext PO files, 'file' = EXPERIMENTAL document files
      of various types). If 'file' is used, transDir must not be the same as or
      nested within srcDir, and vice versa.

    projectVersion
      User property: zanata.projectVersion
      Project version slug (id) within Zanata server.

    pullSrc
      User property: zanata.pullSrc
      Export source-language text from Zanata to local files, overwriting or
      erasing existing files (DANGER!). This option is deprecated, replaced by
      pullType.

    pullType (Default: trans)
      User property: zanata.pullType
      Type of pull to perform from the server: 'source' pulls source documents
      only. 'trans' pulls translation documents only. 'both' pulls both source
      and translation documents.

    purgeCache (Default: false)
      User property: zanata.purgeCache
      Whether to purge the cache before performing the pull operation. This
      means that all documents will be fetched from the server anew.

    skip
      User property: zanata.skip
      (no description available)

    srcDir (Default: .)
      User property: zanata.srcDir
      Base directory for source-language files

    transDir (Default: .)
      User property: zanata.transDir
      Base directory for target-language files (translations)

    url
      User property: zanata.url
      Base URL for the server. Defaults to the value in zanata.xml (if
      present).

    useCache (Default: true)
      User property: zanata.useCache
      Whether to use an Entity cache when fetching documents. When using the
      cache, documents that have been retrieved previously and have not changed
      since then will not be retrieved again.

    userConfig (Default: ${user.home}/.config/zanata.ini)
      User property: zanata.userConfig
      Client configuration file for Zanata.

    username
      User property: zanata.username
      Username for accessing the REST API. Defaults to the value in zanata.ini.

```

**Comment by mbiarnes** [comment]
@Geoffrey: I spent a lot of time with this and didn't find the way how to configure the maven-zanata-plugin. Al other zanata concerned projects have this in the -gitignore and it works. Right now optaplanner-wb is the only project which tries to upload the empty directory org.aptaplanner.

**Comment by ge0ffrey** [comment]
@mbiarnes Ok, thanks for trying to avoid this workaround. I've merged it.
Can you report an upstream issue to the maven zanata plugin project that their generated files should be located under the target directory by default?

**Pull request merged**
