### PR TITLE
PLANNER-617: Workbench: Construction Heuristics - Add support for EntitySorterManner & ValueSorterManner

### PR DESCRIPTION
**Pull request by mcimbora**
This PR reuses classes from optaplanner-core - a new module was introduced (optaplanner-wb-upstream-model) which purpose is to aggregate external dependencies to be used on the client-side

### CODE REVIEW

**Comment by mcimbora** [comment]
Looks like there's an issue with droolsjbpm-knowledge

`[ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.jms:jboss-jms-api_2.0_spec:jar is missing. @ org.kie:kie-api:[unknown-version], /home/jenkins/workspace/optaplanner-wb-pullrequests/upstream-repos/droolsjbpm-knowledge/kie-api/pom.xml, line 164, column 17`

**Comment by psiroky** [comment]
@mcimbora I think you need to rebase your droolsjbpm-build-bootstrap branch to get the latest changes from master (to get the version for the jms-2.0-spec jar)

**Comment by mcimbora** [comment]
@psiroky Thanks for the hint, I repushed the branch.

**Comment by mcimbora** [comment]
Do not merge yet, this will require support for comparator definition. Anyway it would be nice to get opinion on the introduction of the new module for reusing optaplanner classes.

**Comment by ge0ffrey** [comment]
Implementing the comparator definition in a user friendly way in a UI will prove challenging, this is not a trivial thing to do. Let's discuss tomorrow at our meeting.

But I agree that there's little point to support these Manners without supporting comparators... (not to mention weightfactories)

**Comment by mcimbora** [comment]
Closing, will reopen once https://github.com/droolsjbpm/optaplanner-wb/pull/90 & https://github.com/droolsjbpm/optaplanner-wb/pull/94 are integrated.

**Pull request closed without merging**
