### PR TITLE
GUVNOR-2673 Default ExceptionHandler that pops up any uncaught RuntimeException

### PR DESCRIPTION
**Pull request by mcimbora**

### CODE REVIEW

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
@mcimbora did you check jbpm-console-ng as well for call site that include the DefaultErrorCallback?

**Comment by csadilek** [comment]
@mcimbora and a second question :), did you also want any unhandled error to be displayed in the message console (in addition to the notification popup)?

**Comment by mcimbora** [comment]
@csadilek Thanks, I issued a PR for jbpm-console-ng https://github.com/droolsjbpm/jbpm-console-ng/pull/485. Regarding message logging, by default the exceptions are logged to console as well, as default exception handler provided by GWT is invoked as well (which logs to console). Credit goes to @manstis here for figuring this out.

**Comment by csadilek** [comment]
@mcimbora @manstis nope, that's not true. The default exception handler only logs to the console in SuperDevMode, not production mode, where it won't be set. Also, I was referring to the message console in the WB which I thought you wanted to log to as well (may have misunderstood in our meeting).

**Pull request merged**
