### PR TITLE
RHBRMS-2565: No data object has been opened message shown after opening data object

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @mcimbora would you mind review this PR.

The Domian editor needs basically to be ApplicationScoped

Thanks!

**Comment by mcimbora** [comment]
Hi @wmedvede I'm ok with the change.

**Comment by wmedvede** [comment]
Hello  @manstis  would you mind merge this PR?

It's complementary to the already merged into master 
https://github.com/droolsjbpm/kie-wb-common/pull/450

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
Jenkins retest this.

**Pull request merged**
