### PR TITLE
PatternFly UI fixes to workbench

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by Rikkola** [comment]
+1

**Comment by ge0ffrey** [comment]
Exact duplicate of https://github.com/droolsjbpm/optaplanner-wb/pull/23 - closing this one so the other one can live :)

**Comment by psiroky** [comment]
@ge0ffrey this is a PR for different branch (master), the other one is for 6.4.x. I believe we need both (assuming the change should land on 6.4.x as well).

**Comment by ge0ffrey** [comment]
Reopened

@psiroky Thanks Petr!
@cristianonicolai Ignore my comment above, sorry.

**Comment by ge0ffrey** [comment]
Merged, thanks Cristiano

**Pull request merged**
