### PR TITLE
Upgrade to GWT 2.8.0-rc1

### PR DESCRIPTION
**Pull request by csadilek**
Needs:

droolsjbpm/droolsjbpm-build-bootstrap#250
errai/errai#184
uberfire/uberfire#461

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (but `ecj` comment probably needs investigating as suggested by @psiroky)

**Comment by csadilek** [comment]
ecj comment removed

**Comment by manstis** [comment]
+1 to merge (when green).

**Comment by csadilek** [comment]
jenkins please fetch the latest snapshots and retest this.

**Comment by csadilek** [comment]
jenkins I know you can do it. retest this.

**Comment by csadilek** [comment]
jenkin we will get through this together. retest this.

**Comment by csadilek** [comment]
jenkins retest this.

**Pull request merged**
