### PR TITLE
optaplanner-wb-webapp: Include uberfire-security-management-* compile source artifacts

### PR DESCRIPTION
**Pull request by mcimbora**
Fixes compilation issues after https://github.com/uberfire/uberfire/pull/541 had been merged.

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]
+1

**Comment by mcimbora** [comment]
The compilation issue causing build failure will be resolved once https://github.com/droolsjbpm/kie-wb-common/pull/525 is in.

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
jenkins retest this. (jbpm issue resolved.)

**Comment by csadilek** [comment]
+1

**Pull request merged**
