### PR TITLE
PLANNER-629 Workbench: Solver configuration files not recognized in Project Explorer 

### PR DESCRIPTION
**Pull request by mcimbora**

### CODE REVIEW

**Comment by mcimbora** [comment]
jenkins retest this.

**Comment by ge0ffrey** [comment]
+1

Side note: Do we have any consistency yet that we're going for the extension ".solver.xml" (if that's possible everywhere), instead of ".solver"? Consistency means that all examples, docs, etc use the same one. The advantage of ".solver.xml" over ".solver" is that the former is opened in IntelliJ on nautilus or windows explorer by a XML editor by default. But it caused some issues originally for the workbench. Note that for full consistency, we'll also need to adjust the optaplanner engine's examples...

**Comment by mcimbora** [comment]
Looking at the test failures..

**Comment by mcimbora** [comment]
@ge0ffrey `.solver` extension shouldn't be there at all. I think it's side effect of appending .solver.xml extension to new solver configurations. I'll look into it.

**Comment by mcimbora** [comment]
Created an issue for the problem mentioned above: https://issues.jboss.org/browse/PLANNER-630

**Pull request merged**
