### PR TITLE
PLANNER-823: ScoreHolder support does not work in Guided Decision Tables

### PR DESCRIPTION
**Pull request by mcimbora**
Part of:
https://github.com/kiegroup/drools/pull/1373
https://github.com/kiegroup/drools-wb/pull/550
https://github.com/kiegroup/optaplanner-wb/pull/188

### CODE REVIEW

**Comment by ge0ffrey** [comment]
jenkins retest this

**Review by manstis — APPROVED** [review]

**Comment by mcimbora** [comment]
Jenkins retest this please

**Comment by mcimbora** [comment]
Jenkins retest this.

**Comment by manstis** [comment]
Jenkins retest this.

**Comment by ge0ffrey** [comment]
@manstis as its parts of an ensemble that includes drools-wb, will you merge?

**Comment by manstis** [comment]
@ge0ffrey Yes.

**Pull request merged**
