### PR TITLE
latest Zanata translation changes in optaplanner-wb from 2016-09-02

### PR DESCRIPTION
**Pull request by kiereleaseuser**

### CODE REVIEW

**Comment by mcimbora** [comment]
I suggest to reject this PR, as this keeps the properties files completely out of sync (not that they would be in sync right now). I issued zanata push-module locally to enforce alignment with the codebase. Note this requires integration of https://github.com/droolsjbpm/optaplanner-wb/pull/99.

**Comment by csadilek** [comment]
@mcimbora not sure I understand. Can you elaborate?

**Comment by mcimbora** [comment]
@csadilek Sure. Let me show what I mean on a simple example. This is the base for all translated files in domain-editor-client module https://github.com/droolsjbpm/optaplanner-wb/blob/master/optaplanner-wb-screens/optaplanner-wb-domain-editor/optaplanner-wb-domain-editor-client/src/main/resources/org/optaplanner/workbench/screens/domaineditor/client/resources/i18n/DomainEditorConstants.properties. The PR removes entries, which are present in the aforementioned file (e.g. PlannerDataObjectEditorViewImpl.PlannerSettingsLabel), which I considered wrong.

After examining the state of translation strings in zanata system, it was obvious that there was inconsistency between the properties files in the codebase and the system (i.e. majority of entries were missing). I used mvn zanata:push-modules to synchronize the state. Future state pull from zanata will resolve the translations correctly (once the translation process is complete).

**Comment by csadilek** [comment]
thanks for the explanation, @mcimbora

**Pull request closed without merging**
