### PR TITLE
JBPM-4833 - Data Modeller MVP, Tests, and related improvments

### PR DESCRIPTION
**Pull request by wmedvede**
The following commit includes MPV improvments, tests, and small fixes for the following components.

```
- PlannerDataObjectEditor
- PlannerDataObjectFieldEditor
```

### CODE REVIEW

**Comment by wmedvede** [comment]
The following PRs
droolsjbpm/droolsjbpm-build-bootstrap#109 
https://github.com/droolsjbpm/kie-wb-common/pull/158 should be merged into master before this one.

**Comment by wmedvede** [comment]
Hello @manstis 
would you mind review this PR?

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
master: b75bb8c8fc74a8abf6294dcd2f490c81d7414962

**Pull request closed without merging**
