### PR TITLE
[7.0.x] PLANNER-805: Workbench: Planning Solution checkbox gets incorrectly disabled when current data object == PlanningSolution

### PR DESCRIPTION
**Pull request by mcimbora**
7.0.x version of https://github.com/kiegroup/optaplanner-wb/pull/166

### CODE REVIEW

**Comment by manstis** [comment]
@mcimbora What's the point in this PR?! 7.0.0.Final is being released tomorrow AFAIK..

**Review by manstis — APPROVED** [review]

**Review by ge0ffrey — APPROVED** [review]

**Comment by ge0ffrey** [comment]
jenkins retest this
[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000728500000, 920649728, 0) failed; error='Cannot allocate memory' (errno=12)

**Comment by ge0ffrey** [comment]
jenkins test this

**Comment by ge0ffrey** [comment]
Merged this because it needed to make 7.0.0.Final

**Pull request merged**
