### PR TITLE
DROOLS-3425 : Unexpected behavior of docks when multiple editors are opened

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-3425

https://github.com/kiegroup/kie-wb-common/pull/2503
https://github.com/kiegroup/drools-wb/pull/1082
https://github.com/kiegroup/jbpm-designer/pull/837
https://github.com/kiegroup/jbpm-wb/pull/1309
https://github.com/kiegroup/optaplanner-wb/pull/327

### CODE REVIEW

**Review by jomarko — APPROVED** [review]
@Rikkola thank you, `onClose` is not touched this time, however maybe we could add `@Override`. Just trying be consistent with my review.

**Comment by Rikkola** [comment]
@jomarko yep it is good practice to use Override.

**Comment by Rikkola** [comment]
@jomarko good pick. It also needed super.onClose();

**Review by manstis — APPROVED** [review]

**Review by yurloc — APPROVED** [review]
LGTM. Couldn't verify by running the `optaplanner-wb` webapp because it's broken (on master):
```
14:25:37,316 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.unit."optaplanner-wb.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."optaplanner-wb.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1728)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type AuthenticationService with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 9 of [BackedAnnotatedConstructor] @Inject public org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImpl(@Named IOService, CopyService, DeleteService, RenameService, Event<ResourceOpenedEvent>, DecisionTableXLSConversionService, GenericValidator, CommentedOptionFactory, AuthenticationService)
  at org.drools.workbench.screens.dtablexls.backend.server.DecisionTableXLSServiceImpl.<init>(DecisionTableXLSServiceImpl.java:0)
  Possible dependencies: 
  - Managed Bean [class org.jboss.errai.security.server.PicketLinkAuthenticationService] with qualifiers [@Any @Default],
  - Managed Bean [class org.uberfire.ext.security.server.ServletSecurityAuthenticationService] with qualifiers [@Any @Default]
```
We should delete this repository and move the editors to `drools-wb`.

**Review by kkufova — APPROVED** [review]
:+1:

**Pull request merged**
