### PR TITLE
AF-1079,PLANNER-1091 Fix SolverConfig validation

### PR DESCRIPTION
**Pull request by yurloc**
Followup to kiegroup/kie-wb-common/pull/1537.

Fixes https://issues.jboss.org/browse/PLANNER-1091.

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]

**Comment by Rikkola** [comment]
I can get this into 6.5.x and 7.7.x. Thank you for this PR.

**Comment by jomarko** [comment]
@Rikkola probably also into 7.5.x?

**Comment by Rikkola** [comment]
@jomarko right. Too many branches to keep track of.

**Comment by jomarko** [comment]
I just double checked to be sure, 7.5.x shown below:

screenshot from 2018-05-04 12-33-03

**Pull request merged**
