### PR TITLE
PLANNER-784: Workbench: AbstractSolution.score can't be marshaled when using JAXB

### PR DESCRIPTION
**Pull request by mcimbora**
Override getScore getter in AbstractSolution implementations so that JAXB can figure out a correct type of the score used. Additionally I polished the implementation of a score change logic.

@ge0ffrey This is a WB side of the PLANNER-784 fix.

Part of:
- https://github.com/kiegroup/optaplanner-wb/pull/158
- https://github.com/kiegroup/kie-wb-common/pull/869
- https://github.com/kiegroup/kie-wb-playground/pull/23

### CODE REVIEW

**Review by ederign — DISMISSED** [review]
@mcimbora  can you please take a look on the conflicts?

**Comment by mcimbora** [comment]
@ederign I updated the PR. Depends on https://github.com/kiegroup/kie-wb-common/pull/869, which needs to be merged first

**Comment by ederign** [comment]
@wmedvede @manstis can one of you guys take a look on this when you have a chance?

**Review by ge0ffrey — APPROVED** [review]
Approved from my side, but matej said "This one needs to be changed too, I'll reach out to Mike (or some other WB folks) once done"

**Comment by mcimbora** [comment]
@wmedvede @manstis @ge0ffrey PR updated.

**Comment by manstis** [comment]
@mcimbora Could you please clarify @ge0ffrey comment "Approved from my side, but matej said "This one needs to be changed too, I'll reach out to Mike (or some other WB folks) once done".. Do I need to wait for anything before merging?

**Comment by mcimbora** [comment]
@manstis Sure, at the time I wrote the comment, there were still some changes required. Pushed & asked Walter for a review.

**Pull request merged**
