### PR TITLE
UF-305 Upgrade GwtBootstrap to version 0.9.3

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/droolsjbpm/kie-wb-common/pull/407

**Comment by manstis** [comment]
+1 to merge (with others).

**Comment by csadilek** [comment]
@mcimbora @cristianonicolai this is in conflict now after the refactoring to Errai UI. Can you take a look if this is still needed? If so, the conflict is easy to resolve and we can merge this in separately. Thanks!

**Comment by cristianonicolai** [comment]
@csadilek I did check that Errai's `@EventHandler` handles the ChangeEvent for the select as expected, so no need to push this PR, thanks.

**Pull request closed without merging**
