### PR TITLE
PLANNER-789: WorkBench: Some Solution Score Type does not work at 'Add a new action' menu

### PR DESCRIPTION
**Pull request by mcimbora**

### CODE REVIEW

**Comment by manstis** [comment]
@mcimbora Do we need any tests to prevent a re-occurrence of the issue!?

**Comment by mcimbora** [comment]
@manstis PR updated with plugin tests. Thanks.

**Comment by mcimbora** [comment]
Jenkins retest this.

**Review by manstis — APPROVED** [review]

**Comment by manstis** [comment]
@mcimbora OK with me... I assume @ge0ffrey is the "merging" Gate Keeper for Optaplanner...

**Pull request merged**
