### PR TITLE
Enable findbugs.failOnViolation

### PR DESCRIPTION
**Pull request by tomasdavidorg**
Enables findbugs plugins. See the description in https://github.com/kiegroup/drools-wb/pull/530

### CODE REVIEW

**Comment by mcimbora** [comment]
@tomasdavidorg From drools-wb#530 "To check if your changes break some constraint just add -Dfull at the end of your mvn command". Does it mean it's not enabled by default? I can imagine sooner or later someone forgets to perform the check before merging the changes & pushes faulty code into the repository, could you please elaborate?

**Comment by ge0ffrey** [comment]
Tomas, is there a list of which findbugs violations fail the build? I presume it's a minimal list (for now at least)?

**Comment by jhrcek** [comment]
The `-Dfull` property is enabled in optaplanner-wb-pullrequests job on kie-ci jenkins which runs on every pull request, but is not enabled by default. You can see it's been running for some time already e.g. base on https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/optaplanner-wb-pullrequests/258/ which shows FindBugs summary at the bottom. This change only makes that build fail when new "serious"  bug is introduced.

Findbugs plugin configuration is inherited from [this pom](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L1184-L1201) and is set to maxRank 6, which from QE experience are almost certain to be bugs. Unfortunately I'm not aware of any list of bug patterns with rank information :-/

**Comment by ge0ffrey** [comment]
thanks, makes sense. Sounds like usefull for the optaplanner repo too.

**Review by mcimbora — APPROVED** [review]

**Pull request merged**
