### PR TITLE
Clean up dependencies

### PR DESCRIPTION
**Pull request by yurloc**
Depends on:
kiegroup/appformer/pull/378
kiegroup/droolsjbpm-build-bootstrap/pull/763

### CODE REVIEW

**Review by rsynek — APPROVED** [review]
LGTM

**Comment by ge0ffrey** [comment]
jenkins retest this

**Review by ge0ffrey — APPROVED** [review]

**Comment by jhrcek** [comment]
@yurloc I'm afraid this might have caused the following failures in daily kieAllBuild:

https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/kieAllBuild-master/job/kieAllBuild-master/340

```
04:44:11.981 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project optaplanner-wb-solver-editor-backend: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
04:44:11.984 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project optaplanner-wb-solver-editor-backend: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
```

**Comment by ge0ffrey** [comment]
```
14:56:42 [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ optaplanner-wb-guided-rule-editor-backend ---
14:56:42 [INFO] Installing /home/jenkins/workspace/optaplanner-wb/optaplanner-wb-screens/optaplanner-wb-guided-rule-editor/optaplanner-wb-guided-rule-editor-backend/target/optaplanner-wb-guided-rule-editor-backend-7.9.0-SNAPSHOT.jar to /home/jenkins/.m2/repository/org/optaplanner/optaplanner-wb-guided-rule-editor-backend/7.9.0-SNAPSHOT/optaplanner-wb-guided-rule-editor-backend-7.9.0-SNAPSHOT.jar
14:56:42 [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
14:56:42 Duplicate classes found:
14:56:42 
14:56:42   Found in:
14:56:42     javax.el:javax.el-api:jar:3.0.0:provided
14:56:42     org.jboss.spec.javax.el:jboss-el-api_3.0_spec:jar:1.0.9.Final:test
```

**Pull request merged**
