### PR TITLE
PLANNER-537: Workbench Solver Editor: remove bendable types from solver score configuration

### PR DESCRIPTION
**Pull request by mcimbora**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
+1

**Comment by ge0ffrey** [comment]
ok to test

**Comment by csadilek** [comment]
@psiroky can you add @mcimbora to our github org so his PRs don't have to be verified? thanks.

**Comment by psiroky** [comment]
@csadilek way ahead of you :) (added him ~30 mins back)

**Pull request merged**
