### PR TITLE
Upgrade wildfly-dist to 10.0.0.Final.

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
+1

@psiroky in optaplanner (not wb) there's optaplanner-webexamples (which doesn't use gwt, nor wb, nor uf). That uses wildfly too and currently declares it own version - I think it's better if that streamlines to the kie's wildfly version too maybe? See https://github.com/droolsjbpm/optaplanner/blob/master/optaplanner-webexamples/pom.xml#L27

**Comment by psiroky** [comment]
@ge0ffrey I agree we should unify the version. I am just not sure if to use `version.org.wildfly` or `version.org.wildfly10` . We may need to test on wildlfy 11 as well in future, so the later would then be more aligned with `version.org.wildfly11`, but I may be just over-engineering this :) WDYT?

**Comment by ge0ffrey** [comment]
@psiroky I think we should have version.org.wildfly which is the default wildfly version that applies to most poms - then we can also add the properties version.org.wildfly10 and version.org.wildfly11 for those specific poms that don't need the default. Wdyt?

**Comment by psiroky** [comment]
@ge0ffrey sounds good. I will do the changes as part of the next IP BOM upgrade (don't want to create PRs just for one liners...)

**Pull request merged**
